### ISSUE TITLE
fine-scale covariance model

### ISSUE THREAD

**Issue by Jing25** [Raphael-Nussbaumer-PhD/A2PK#1]
Hi, 

Great work and thanks for sharing! I'm new to A2PK and I'm curious that where the covariance model parameters come from (the first several lines of your example)? Is it from the coarse image covariance model? Your method doesn't need a fine scale original image, does it?

```

covar.model='exponential'; covar.range=[20 20]; covar.var=1; covar.azimuth=0;
covar = covarIni(covar);
```

Thanks,
Jing

**Comment by Rafnuss** [comment]
Hi Jing,
Thanks for your kind word. In the template script (https://rafnuss-phd.github.io/A2PK/script),  the *fine* scale original image is defined arbitrarily for a synthetic case study. You can change it as you wish. The two line you mentioned defined the the fine-scale covariance. The coarse scale image is simply defined based on the upscaling from the resolution of the fine-scale to the coarse scale (`Z.dx=4;Z.dy=4;`).

Let me know if you have more question or if I can help

**Comment by Jing25** [comment]
If I only have a coarse scale image, can I use your script to downscale it to the fine scale?

**Comment by Rafnuss** [comment]
You will need the covariance model of the fine scale in addition. Then yes

**Comment by Jing25** [comment]
I see. Thank you for your explanation!
